### ISSUE TITLE
400 error with getSurvey

### ISSUE THREAD

**Issue by jakemsnyder** [JasperHG90/qualtRics#17]
Error in qualtRicsResponseCodes(res) : 
  Qualtrics API raised a bad request (400) error - Please report this on https://github.com/JasperHG90/qualtRics/issues

I get the error with both the main package and development version. Was working fine before I updated today, I think the last time I downloaded was late December. `getSurveys` works as intended.

**Comment by jakemsnyder** [comment]
Update: needed to fix the root_url to include /API/v3/. Now I get a 404 error, but I'm confident I have the correct survey ID. I tried multiple different IDs and still get the error.

**Comment by JasperHG90** [comment]
Hey Jake,

Thanks for notifying me of this error. You don't need to append the '/API/v3/' part to the root url, as that is done by [this](https://github.com/JasperHG90/qualtRics/blob/master/R/utils.R#L175-L178) function. Adding it twice causes the 403 error.

If I understand you correctly, you were able to retrieve the results for your survey before using the current version (0.3) of qualtRics available from CRAN, and that now both the CRAN version as well as the package version found on the master branch of this repository return this error? Does it return this error for all your surveys or just the one you're trying to retrieve?

The 400 response code occurs because something about the request [is invalid](https://api.qualtrics.com/docs/response). Could you post the exact command you're using here or PM it to me?

Thanks!

**Comment by jakemsnyder** [comment]
I have no idea what changed, but I just tried it again and it works fine now... Thank you for reaching out, but I'll close the issue since it's working again :) Appreciate the help!

**Comment by JasperHG90** [comment]
Glad your issue sorted itself out!
