### ISSUE TITLE
Invalid input error when running on Ubuntu 

### ISSUE THREAD

**Issue by cfitzge1** [JasperHG90/qualtRics#22]
Hi,
I'm having an issue with qualtRics where when I run my script to download results of a survey to a specified directory, I get the error message below:

```
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  invalid input found on input connection '/tmp/RtmpVQGNZ1/<my_survey_name>.csv'
```
What is odd is that this is not the folder I indicate to save the file to, and I only get 14 rows of data read (out of ~1500).

I have changed the permissions of that folder, thinking that may help, and it hasnt.

If I put NULL in save_dir, I still get the same error.

Thanks in advance!

**Comment by JasperHG90** [comment]
Hi,

Thanks for reporting this to me! I've not come across this error before.

qualtRics downloads surveys into a temp folder and, if specified, saves the result in a user-defined path if the user provides it. That's why the path seems wrong.

I'll be away from my computer until Friday. Can I contact you privately to get more information about this error? It's hard to reproduce such things on my end.

**Comment by JasperHG90** [comment]
@cfitzge1 : could you review my request? I'd like to resolve this issue for you and others!

**Comment by JasperHG90** [comment]
Closed because OP doesn't respond.
