### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by ThomasWilli** [JasperHG90/qualtRics#60]
Hi
Thanks for the great package.

`getSurveys()` keeps telling me 
     `Qualtrics API raised an authentication (401) error - you may not have the required authorization. Please check your API key and root url.`

Well, obviously that seems (and most likely is) very stupid of me. However, I followed the documentation and registered using:
    `registerOptions(api_token="MYTOKEN", root_url="ROOTURL")`

I also consulted the API Docs of Qualtrics and can't come up with a different rooturl... Do you have any advice on this?

Thanks in advance.
Tom

**Comment by frankvanpraag** [comment]
Hi Tom,

Did you perhaps put http:// in the root_url? In case it helps, here are the commands that work for me on the R console:

install.packages("qualtRics")
library(qualtRics)
registerOptions(api_token=“aaiudoiasudo_goobledigook_iasodiausoiduasoidu", root_url="au1.qualtrics.com")
set_config(config(ssl_verifypeer = 0L))
mysurvey <- getSurvey(surveyID = 'SV_XXXXXXXXX', save_dir = "/Users/XXXXX/R/qualtRics/", verbose=TRUE, uselabels=FALSE, force_request = TRUE)
lastResponseId.rds <- tail(mysurvey$ResponseID,1)

Kind regards,

Frank

 <https://www.qualtrics.com/>

**Comment by ThomasWilli** [comment]
Hmm... No I did not. Strange error. 

Following the example provided [here I](https://cran.r-project.org/web/packages/qualtRics/vignettes/qualtRics.html)'m still getting the `Error in qualtRicsResponseCodes(res, raw = raw) : 
  Qualtrics API raised an authentication (401) error - you may not have the required authorization. Please check your API key and root url.`

**Comment by frankvanpraag** [comment]
I’m pretty sure your Token is outdated. Log into your qualtrics account and copy your current Token into your R code:



I managed to recreate the same error by regenerating a new token and trying the old (invalidated) token:



Hope that helps. Kind regards,

Frank

**Comment by JasperHG90** [comment]
Hi Thomas,

Thanks for your comment. Like @frankvanpraag suggested, the most likely situation is that your token is outdated. That error only occurs when authentication with the Qualtrics API fails. You can request a new token in your qualtrics dashboard. If the problem persists, try using your token/root url using the tool offered in the qualtrics API docs (e.g. https://api.qualtrics.com/docs/create-response-export, bottom of page) and perhaps contact support staff at Qualtrics.

I'm closing this issue since this is not an issue related to the qualtRics package.

Best,

Jasper.
