### ISSUE TITLE
getSurveyQuestionChoices

### ISSUE THREAD

**Issue by nfrimando** [JasperHG90/qualtRics#65]
Hello Jasper,

First off, thanks for spearheading this qualtRics package. Definitely found it useful myself.

I was wondering if there are plans to develop a getSurveyQuestionChoices function which, by the name, requires (1) surveyID and a (2) question ID inputs to output the list of possible choices that a question may have. I thought of using this for mapping purposes if ever I need to use a data schema.

If yes, do you think it's nearing completion? and if not, is there anyway for me to try contributing to the package for this function?

Thanks a lot, this package is really a big help.

**Comment by JasperHG90** [comment]
Thanks for your comment.

For development purposes I use a function called 'metadata'. This function works much like the others in that it pulls in API data from the [surveys endpoint](https://api.qualtrics.com/docs/get-survey). I thought about adding it earlier but haven't done so yet because it wasn't a priority. I don't mind adding it in the next iteration if you'd like this functionality.

**Comment by nfrimando** [comment]
Actually, the getSurveyMetadata() function I saw in utils.R may be very useful. For my case, I can build on it to create the getSurveyQuestionChoices() function I was alluding to. Alright, that is awesome. Looking forward to the next iteration. In the meantime, I'll work off your source code. 

Thanks a lot!

**Comment by JasperHG90** [comment]
See [utils.R](https://github.com/JasperHG90/qualtRics/blob/development/R/utils.R#L402-L484) in development branch
